name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Dev-ops-Project/src/TestDirection.java 
    - name: Set up JDK 1.8
      uses: Dev-ops-Project/src/TestDirection.java 
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
